version: '3'
services:
  pptag:
    image: arehbein/pptag:latest
    restart: always
    volumes:
      - /share/Photos/:/Photos
      # needs to be an absolute path
      - /share/Container/pptag/config.py:/app/pptag/config.py:ro
